### PR TITLE
Fixes UTC offset timezone handling and rendering

### LINKED ISSUE #23: Properly handle UTC offset timezones
## Symptoms

When a booking is made with a `client_tz` in the form of `UTC[+|-](\d)(:\d)?`, the timezone used is the WordPress server timezone.

## Steps to Reproduce

**In EDD Bookings:**

1. Set up a service with a UTC offset timezone.
2. From the wizard, select a booking for this service and add it to the cart.

**Alternatively:**

1. Set up a service and enable the option to allow customers to change timezone.
2. From the wizard, select a UTC offset timezone and add the booking to the cart.

_For both cases, the symptoms should be visible in the cart page:_  
1. The booking times should be in the WordPress server timezone.
2. The timezone for the booking should also be the WordPress server timezone.

## Possible Cause

The timezone name parsing is failing to parse the client or service timezone, resulting in the fallback timezone being used. There is no fallback timezone set in the config, so the next fallback is used, which is the WordPress timezone.

## Recommended Solution

Require PHP `5.5.10` to allow instantiation of a `DateTimeZone` object with offset strings, such as `"+0200`.

The offset string will need to be derived from the UTC timezone name, by removing the `"UTC"` prefix and the colon, and adding any necessary padding zeroes:

```
"UTC+2"    -> "+0200"
"UTC-5:30" -> "-0530"
```

For the above timezones, `DateTimeZone#getName()` returns a name similar string:

```
"+0200" -> "+02:00"
"-0530" -> "-05:30"
```
Therefore, for displaying the timezone name, a simple first-character check should suffice for detection, and simply adding a `"UTC"` prefix will amend the name.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #23

### CODE REVIEW

File: src/Module/GetBookingDisplayTimezoneCapableTrait.php [hunk 1]
```diff
@@ -95,49 +100,132 @@ protected function _getDisplayTimezone($bookingData)
...
      *
-     * @return DateTimeZone The timezone instance.
+     * @return DateTimeZone|null The timezone instance, or null if the booking does not have a client timezone set.
+     *
+     * @throws OutOfRangeException If the booking client's timezone is invalid.
      */
     protected function _getBookingClientTimezone($bookingData)
     {
-        $clientTzName = $this->_containerGet($bookingData, 'client_tz');
+        if (!$this->_containerHas($bookingData, 'client_tz')) {
```
Comment (XedinUnknown) [inline src/Module/GetBookingDisplayTimezoneCapableTrait.php]: Can has a `null` value. I think you should account for that.

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

File: src/Module/GetBookingDisplayTimezoneCapableTrait.php [hunk 2]
```diff
@@ -106,7 +106,11 @@ protected function _getDisplayTimezone($bookingData)
      */
     protected function _getBookingClientTimezone($bookingData)
     {
-        if (!$this->_containerHas($bookingData, 'client_tz')) {
+        $clientTz = $this->_containerHas($bookingData, 'client_tz')
+            ? $this->_containerGet($bookingData, 'client_tz')
+            : null;
+
+        if (empty($clientTz)) {
```
Comment (XedinUnknown) [inline src/Module/GetBookingDisplayTimezoneCapableTrait.php]: I think that this is an opportunity for a bug, similar to what lead to this PR in the first place. It's the `null` value that indicates the absence of a timezone. `""` is a present timezone, but it is invalid, and should be treated that way.

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

File: src/Module/GetBookingDisplayTimezoneCapableTrait.php (hunk 2 above)
Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: There is nothing that says that `""` is a present timezone. In fact, for most data models with known schemas, non-present values have meaningful defaults. This is actually the case with EDD Bookings, where a booking retrieved from the database will have the `client_tz` key present, but will have a `""` value. Or maybe a `NULL` value. I don't recall how I set up that table. But it shouldn't matter.

Comment (XedinUnknown) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: `""` is a value. `null` is a value that specifically indicates the absence of a value. The code should attempt to create a timezone object with anything that is a present value. And it should fail if that value is invalid.

However, if the underlying data happens to be using `""` as a default to mean "no value" instead of `NULL`, then I will accept. But please confirm.

Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: Confirmed.

Comment (XedinUnknown) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: What about other empty values? `0` should throw, not return `null`.

Comment (XedinUnknown) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: Same for `"0"`.

Comment (XedinUnknown) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: > should throw

Rather, whether to throw should be up to the constructor of the date-time object. That's what I meant.

Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: Ah, good point. That should definitely be classified as an invalid timezone.

What do you think about utilizing PHP's `null` to `string` casting for an empty string check?

```
if (strlen((string)$tz) === 0) return null;
```

Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: _Aside_: I'm trying to find the best way to catch both empty strings and nulls, without having to go old school.

Comment (XedinUnknown) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: That sounds much better.

Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: I think I hit my head or something.

Comment (mecha) [reply src/Module/GetBookingDisplayTimezoneCapableTrait.php]: Happy days! [`strlen` accepts `null` and returns `0`.](https://3v4l.org/0s1Gs)

**Review by XedinUnknown — APPROVED** [review]
